---
title: "Code-playground"
author: "Ryan O'Dea"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(
  ggplot2,
  gganimate,
  tidyquant,
  tidyverse,
  lubridate,
  ggExtra,
  wesanderson
)
```

## ggExtra - Side Density Plots
```{r}
#Chess Games from Lichess (https://www.kaggle.com/datasnaek/chess) ------------------------
chess <- read.csv(file = "games.csv")
chess <- chess %>% filter(victory_status != "outoftime")
chess_rated <- chess %>% filter(rated == "TRUE")

#All Rated Games---------------------------------
chess_rated_wins <- chess_rated %>%
ggplot(aes(x = white_rating, y = black_rating, group = victory_status, col = victory_status)) + 
  geom_point(alpha = .5) + 
  theme_gray() + 
  geom_smooth(aes(group = victory_status), se = FALSE) + 
  labs(title = "Lichess White vs Black Rating (Non-Subsetted)",
       subtitle = "Data: https://www.kaggle.com/datasnaek/chess",
       col = "Victory Type") + 
  ylab("Black Rating") + 
  xlab("White Rating") + 
  scale_colour_manual(breaks = c("mate", "resign", "draw"),
                      labels = c("Checkmate", "Resignation", "Draw"),
                      values = c("#1B9E77",
                                 "#D95F02",
                                 "#7570B3"))

all_wins <- ggMarginal(chess_rated_wins, groupColour = FALSE, groupFill = TRUE)


#Where White wins
chess_white <- filter(chess_rated, winner == "white")
chess_rated_white <- chess_white %>%
ggplot(aes(x = white_rating, y = black_rating, group = victory_status, col = victory_status)) + 
  geom_point(alpha = .2) + 
  theme_gray() + 
  geom_smooth(aes(group = victory_status), se = FALSE) + 
  labs(title = "Lichess White vs Black Rating (White Wins)",
       subtitle = "Data: https://www.kaggle.com/datasnaek/chess",
       col = "Victory Type") + 
  ylab("Black Rating") + 
  xlab("White Rating") + 
  scale_colour_manual(breaks = c("mate", "resign"),
                      labels = c("Checkmate", "Resignation"),
                      values = c("#1B9E77",
                                 "#D95F02"))

white_wins <- ggMarginal(chess_rated_white, groupColour = FALSE, groupFill = TRUE)

#Where Black Wins
chess_black <- filter(chess_rated, winner == "black")
chess_rated_black <- chess_black %>%
ggplot(aes(x = white_rating, y = black_rating, group = victory_status, col = victory_status)) + 
  geom_point(alpha = .2) + 
  theme_gray() + 
  geom_smooth(aes(group = victory_status), se = FALSE) + 
  labs(title = "Lichess White vs Black Rating (Black Wins)",
       subtitle = "Data: https://www.kaggle.com/datasnaek/chess",
       col = "Victory Type") + 
  ylab("Black Rating") + 
  xlab("White Rating") + 
  scale_colour_manual(breaks = c("mate", "resign"),
                      labels = c("Checkmate", "Resignation"),
                      values = c("#1B9E77",
                                 "#D95F02"))

black_wins <- ggMarginal(chess_rated_black, groupColour = FALSE, groupFill = TRUE)

ggsave("all_wins.png",
       plot = all_wins,
       height = 10, width = 15, dpi = 900)

ggsave("white_wins.png",
       plot = white_wins,
       height = 10, width = 15, dpi = 900)

ggsave("black_wins.png",
       plot = black_wins,
       height = 10, width = 15, dpi = 900)

```

